# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1
              - destroy_environment
        
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["a2:1f:59:c5:14:37:79:a9:2d:c3:d6:69:18:af:5b:b8"] 
      - run:
          name: Install Ansible
          command: | 
           apk add --update ansible
            # Install Ansible
      - run:
          name: Run Playbook and Configure server
          command: | 
           ansible-playbook -i inventory main.yml

workflows:
  say-workflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure
